### ISSUE TITLE
Missing GovCloud region

### ISSUE THREAD

**Issue by carter3d** [awsdocs/aws-storagegateway-user-guide#10]
Shouldn't GovCloud be listed in the region table for File, Volume, and Tape Gateway?

https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/govcloud-storagegateway.html

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
