### ISSUE TITLE
Broken link to sources.tar

### ISSUE THREAD

**Issue by wolruf** [awsdocs/aws-storagegateway-user-guide#11]
The URI https://s3.amazonaws.com/aws-storage-gateway-terms/sources.tar is a dead link

source:
https://docs.aws.amazon.com/storagegateway/latest/userguide/AboutAWSStorageGatewaySoftware.html

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
