### ISSUE TITLE
Github page for the Squid configuration. 

### ISSUE THREAD

**Issue by emmaylots** [awsdocs/aws-storagegateway-user-guide#25]
Hi,

Please create a separate Github page for the Squid configuration, see below. This will make it easy for the configuration to be retrieved via via curl and used for EC2 Userdata.

#
# Recommended minimum configuration:
#
 
# Example rule allowing access from your local networks.
# Adapt to list your (internal) IP networks from where browsing
# should be allowed
acl localnet src 10.0.0.0/8              # RFC1918 possible internal network

........

Thank you

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
