### ISSUE TITLE
Kubernetes support

### ISSUE THREAD

**Issue by elgalu** [awsdocs/aws-storagegateway-user-guide#26]
It would be nice to have EKS / general Kubernetes support such that users can mount S3 paths directly to pods.

Existing work like https://github.com/ctrox/csi-s3 is not officially maintained by AWS and doesn't use AWS Storage Gateway software.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
