### ISSUE TITLE
[VMware Appliance] Missing information in documentation

### ISSUE THREAD

**Issue by zanhsieh** [awsdocs/aws-storagegateway-user-guide#7]
Hi,

Couple questions below not mentioned in storage gateway documentation (VMware appliance specifically):

- [File Gateway] What is the proper steps for moving the cache disk to different place, in case there's only one cache disk and not possible to arrange another spare cache disk?
- [All Gateway] Just curious if there's any way to completely reset storage gateway appliance without re-uploading .ova to VMWare ESXi.
- [Volume Gateway][File Gateway] Could file storage gateway VMware appliance be used interchangeable with volume storage gateway VMware appliance?
- [Volume Gateway] Could cache volume gateway VMware appliance be used interchangeable with store volume gateway appliance?
- [Volume Gateway][Tape Gateway] How does that differ to tape library gateway VMWare appliance?

Here is my story:

Previously I set up a on-premise storage gateway appliance (VMWare ESXi, the one just support SMB).  Since my colleague reported the performance is far slower than our in-house NFS solution (around ~5x slower), so I started to look into documentation (https://docs.aws.amazon.com/storagegateway/latest/userguide/Optimizing-common.html) to optimize it. Due to several constraints, the best move I could take is just move the cache storage not with the same physical disk as the root of the appliance (really not sure outcome would be the same result since VMWare ESXi already have very good volume isolation). So I powered off the appliance, delete the cache drive, and arrange another drive with exact the same size in different physical datastore, and booted up. The appliance went fine, but AWS storage gateway console shows always show the on-prem appliance is offline even after 4 hours. Go back to Create storage gateway -> ... -> Activate storage gateway always throw me blank screen, saying that the page does not exist.

Since no way to recover back the storage gateway appliance, and no documentation tells how to completely reset the storage gateway appliance, I have to throw off the current appliance VM even it working fine in VMWare console, and re-download the appliance and then re-create it again, which involves re-upload again. If there's a complete reset command from the manual after logging in, then it definitely would save me a lot of time and bandwidth.

Since my colleague and I are in hurry, I downloaded the volume gateway image (cache gateway specifically) and started testing. I found the cache volume gateway no matter what I configure, it always choose same physical store (means appliance boot disk, cache disk, upload buffer disk are all on the same physical store), whereas the documentation does not mention this at all. Also, the procedure to set up on Debian based distribution is also missing.

Hope this get resolved soon.

// Ming

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
