### ISSUE TITLE
Misleading text

### ISSUE THREAD

**Issue by jeffbarr** [awsdocs/aws-storagegateway-user-guide#8]
The documentation at https://docs.aws.amazon.com/storagegateway/latest/userguide/monitoring-file-gateway.html says "You can configure this notification to be delivered to the target message." Delivering a notification to a message does not make any sense.

**Comment by pattipoe** [comment]
Thanks for the feedback. It should read:
You can configure this notification to be delivered to the target as a text message.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
